import './globals.css'
import Nav from './auth/Nav'
import { Roboto } from '@next/font/google'
import QueryWrapper from "./query/QueryWrapper"

const roboto = Roboto({
  subsets: ['cyrillic', 'latin'],
  weight: ['400', '700'],
  variable: '--font-roboto'
})

export const metadata = {
  title: 'PORTiT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} mx-4 md:mx-48 xl:mx-96 bg-gray-200`}>
        <QueryWrapper>
          <Nav />
          {children}
        </QueryWrapper>
      </body>
    </html>
  )
}
