import './globals.css'
import Nav from './auth/Nav'

export const metadata = {
  title: 'PORTiT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
      </body>
    </html>
  )
}
